apiVersion: v1
kind: Service
metadata:
  name: myapp-webapi
  namespace: myapp
  labels:
    app: myapp-webapi
    component: backend
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: myapp-webapi
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP