apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-webapp
  namespace: webinar5
  labels:
    app: myapp-webapp
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-webapp
  template:
    metadata:
      labels:
        app: myapp-webapp
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: your-docker-hub-account/myapp-webapp:2.0
        env:
        - name: ApiSettings__WebApiUrl
          value: "http://myapp-webapi-service.webinar5.svc.cluster.local"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
