apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress-host
  namespace: webinar5
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-webapp-service
            port:
              number: 80
  - host: api.myapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-webapi-service
            port:
              number: 80

